In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [14]:
crime = pd.read_csv('Downloads/durham-police-crime-reports.csv')

In [15]:
crime.head()

,Lati,Long,inci_id,date_rept,hour_rept,yearstamp,monthstamp,date_occu,dow1,hour_occu,...,chrgdesc,csstatus,csstatusdt,addtime,reviewdate,UCR_TYPE_O,DIST,STRDATE,BIG_ZONE,count
0,35.988631,-78.899754,17015455,2017-05-08T20:00:00-04:00,647,2017,5,2017-05-08T20:00:00-04:00,TU,401,...,BURGLARY - FORCIBLE ENTRY,2,2017-05-17T20:00:00-04:00,2017-05-08T20:00:00-04:00,2017-05-14T20:00:00-04:00,NaN,4.0,2017-05-09 0,Zone 3,1
1,35.941756,-78.860863,17015463,2017-05-08T20:00:00-04:00,855,2017,5,2017-05-08T20:00:00-04:00,TU,40,...,LARCENY - FROM MOTOR VEHICLE,2,2017-05-09T20:00:00-04:00,2017-05-08T20:00:00-04:00,2017-05-14T20:00:00-04:00,NaN,4.0,2017-05-09 0,Zone 4,1
2,35.923577,-78.813926,17015466,2017-05-08T20:00:00-04:00,903,2017,5,2017-05-07T20:00:00-04:00,MO,1200,...,LARCENY - ALL OTHER,2,2017-05-14T20:00:00-04:00,2017-05-08T20:00:00-04:00,2017-05-11T20:00:00-04:00,NaN,4.0,2017-05-09 0,Zone 4,1
3,35.955870,-78.998220,17015473,2017-05-08T20:00:00-04:00,1015,2017,5,2017-04-01T20:00:00-04:00,SU,0,...,FRAUD - CREDIT CARD/ATM,2,2017-05-09T20:00:00-04:00,2017-05-08T20:00:00-04:00,2017-05-09T20:00:00-04:00,NaN,3.0,2017-05-09 1,Zone 2,1
4,35.984657,-78.890465,17015488,2017-05-08T20:00:00-04:00,1129,2017,5,2017-04-28T20:00:00-04:00,SA,0,...,LARCENY - FROM MOTOR VEHICLE,1,2017-05-09T20:00:00-04:00,2017-05-08T20:00:00-04:00,2017-05-11T20:00:00-04:00,NaN,5.0,2017-05-09 1,Zone 4,1

In [16]:
print(crime.shape)
crime['chrgdesc'].unique()
crime['chrgdesc'].value_counts()

(125340, 25)

TOWED/ABANDONED VEHICLE                                 12460
BURGLARY - FORCIBLE ENTRY                               11086
LARCENY - FROM MOTOR VEHICLE                            11023
LARCENY - SHOPLIFTING                                    9080
SIMPLE ASSAULT (PHYSICAL ASSAULT NOT AGGRAVATED)         6069
LARCENY - ALL OTHER                                      5072
LARCENY - FROM BUILDING                                  4923
VANDALISM TO AUTO (NOT ACCIDENTAL)                       4490
CALLS FOR SERVICE (NO CRIME)                             4268
AGGRAVATED ASSAULT                                       4004
VANDALISM TO PROP (NOT ACCIDENTAL)                       3656
ROBBERY - INDIVIDUAL                                     2928
LARCENY - AUTOMOBILE PARTS OR ACCESSORIES                2877
DRUG/NARCOTIC VIOLATIONS - POSSESS/SELL MARIJUANA        2675
MOTOR VEHICLE THEFT - AUTOMOBILE                         2527
BURGLARY - NON-FORCED ENTRY                              2354
FRAUD - CREDIT CARD/ATM                                  2012
FOUND PROPERTY                                           1910
DRIVING WHILE IMPAIRED                                   1902
FRAUD - FALSE PRETENSE                                   1757
LOST PROPERTY                                            1581
DEATH INVESTIGATION                                      1469
FRAUD - OTHER                                            1360
ALL TRAFFIC (EXCEPT DWI)                                 1335
FRAUD - IMPERSONATION                                    1269
RUNAWAY                                                  1097
ALL OTHER CRIMINAL OFFENSES                              1063
DV INFO REPORT (NO CRIME)                                1015
SIMPLE ASSAULT-NON PHYSICAL THREAT OR INTIMIDATION        930
MISSING PERSON                                            929
                                                        ...
SEX OFFENSE - INCEST                                        6
DRUG EQUIPMENT/PARAPHERNALIA - MANUFACTURING                5
KIDNAPPING/ABDUCTION                                        5
MOTOR VEHICLE THEFT - RECREATIONAL VEHICLE                  5
SEX OFFENSE - FORCIBLE SODOMY                               4
OBSCENE MATERIAL/PORNOGRAPHY - POSSESSING/CONCEALING        4
HOMICIDE-MURDER/NON-NEGLIGENT MANSLAUGHTER                  3
COUNTERFEITING - MANUFACTURING                              3
CURFEW/LOITERING/VAGRANCY VIOLATIONS                        3
ALL OTHER OFFENSES-BIGAMY/MARRIAGE LAWS                     3
TRUANCY                                                     3
STOLEN PROPERTY - SELLING/DISTRIBUTING                      3
DRUG EQUIPMENT/PARAPHERNALIA - BUYING                       2
PORNOGRAPHY/OBSCENE MATERIAL                                2
WEAPON VIOLATIONS - SELLING/DISTRIBUTING                    2
BLACKMAIL/EXTORTION                                         2
FORGERY - SELLING/DISTRIBUTING                              2
STOLEN PROPERTY - TRANSPORTING                              2
DISORDERLY CONDUCT-UNLAWFUL ASSEMBLY                        2
HOMICIDE - MANSLAUGHTER BY NEGLIGENCE                       2
OBSCENE MATERIAL/PORNOGRAPHY - USING                        2
NON-NEGLIGENT TRAFFIC DEATH                                 1
PROSTITUTION - ASSISTING/PROMOTING                          1
SEX OFFENSE - SEXUAL ASSAULT WITH AN OBJECT                 1
DRUG EQUIPMENT/PARAPHERNALIA - TRANSPORTING                 1
IDENTITY THEFT                                              1
TRESSPASS-LAND UNDER OPTION BY FEDERAL GOVERNMENT           1
ALL OTHER OFFENSES-BRIBERY                                  1
COUNTERFEITING - TRANSPORTING                               1
LIQUOR LAW VIOLATIONS                                       1
Name: chrgdesc, Length: 172, dtype: int64

In [17]:
print(crime.describe())

                Lati           Long       inci_id      hour_rept  \
count  125340.000000  125340.000000  1.253400e+05  125340.000000
mean       35.982706     -78.909036  1.601452e+07    1307.606399
std         0.072622       0.160916  1.417418e+06     613.993056
min        33.566922     -85.569831  5.445817e+06       0.000000
25%        35.956513     -78.928912  1.501209e+07     910.000000
50%        35.989735     -78.904196  1.602333e+07    1340.000000
75%        36.015210     -78.884884  1.703004e+07    1805.000000
max        36.280751     -78.728696  9.905463e+07    2359.000000

           yearstamp     monthstamp      hour_occu       hour_fnd  UCR_TYPE_O  \
count  125340.000000  125340.000000  125340.000000  125340.000000      5296.0
mean     2002.970720       6.373552    1289.515199    1275.566060         1.0
std       161.446098       3.369357     687.120419     639.744381         0.0
min         0.000000       0.000000       0.000000       0.000000         1.0
25%      2015.000000       4.000000     806.000000     822.000000         1.0
50%      2016.000000       6.000000    1400.000000    1320.000000         1.0
75%      2017.000000       9.000000    1843.000000    1800.000000         1.0
max      2018.000000      12.000000    2359.000000    2359.000000         1.0

                DIST     count
count  124705.000000  125340.0
mean        2.723179       1.0
std         1.218176       0.0
min         1.000000       1.0
25%         2.000000       1.0
50%         3.000000       1.0
75%         4.000000       1.0
max         5.000000       1.0

In [18]:
import gmaps
import gmaps.datasets
gmaps.configure(api_key="AIzaSyAcY_d3jJpmc4jwnk6OMYgvFz4wx33uPpI")

In [19]:
locations = crime[['Lati','Long']]
fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations))
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
house = pd.read_excel('durham-nc-neighborhoods-Zillow-Home-Value-Index-TimeSeries (1).xls')

In [9]:
house

,Region Name,Region Type,Data Type,2008-10-15 00:00:00,2008-11-15 00:00:00,2008-12-15 00:00:00,2009-01-15 00:00:00,2009-02-15 00:00:00,2009-03-15 00:00:00,2009-04-15 00:00:00,...,2018-02-15 00:00:00,2018-03-15 00:00:00,2018-04-15 00:00:00,2018-05-15 00:00:00,2018-06-15 00:00:00,2018-07-15 00:00:00,2018-08-15 00:00:00,2018-09-15 00:00:00,Latitude,Longitude
0,Durham,city,All Homes,160300,160200,160100,159900,159800,159600,159300,...,206300,208100,209500,210900,212900,214800,217000,218900,NaN,NaN
1,American Village,neighborhood,All Homes,255700,255900,256000,256200,256200,256100,255900,...,310700,312000,313000,314900,317400,319500,321600,323500,36.017087,-78.969454
2,Colonial Village,neighborhood,All Homes,109100,110000,110900,111600,112300,112900,113800,...,152500,151100,151400,152800,153000,153300,155200,156800,35.189505,-80.869604
3,Duke Forest,neighborhood,All Homes,340200,341300,342400,343300,343900,344500,344900,...,453300,465500,476800,484100,487600,492100,498400,503800,35.585900,-79.018600
4,Duke Park,neighborhood,All Homes,154000,154300,154600,155000,155600,156100,156400,...,273800,275200,273700,271200,269500,269200,271800,275600,36.013667,-78.899723
5,Fairfield,neighborhood,All Homes,310600,309600,308600,307900,307400,306700,305700,...,368900,372000,373900,374700,375200,376500,378100,379400,36.047507,-78.906627
6,Forest Hills,neighborhood,All Homes,260000,261800,263600,265100,266500,267800,268700,...,403800,405100,404800,402300,402600,406400,412900,418600,35.980379,-78.924012
7,Grove Park,neighborhood,All Homes,179900,180000,180100,180200,180100,180200,180200,...,217600,220500,222200,223800,225500,227400,230100,232500,35.973712,-78.818301
8,Hope Valley,neighborhood,All Homes,217700,217500,217300,217000,216700,216200,215600,...,267700,268500,269800,271700,273300,275200,277600,279400,35.949787,-78.961095
9,Hope Valley Farms,neighborhood,All Homes,204300,204400,204500,204500,204500,204300,204000,...,249100,250100,250700,250700,250600,251300,253300,255200,35.946093,-78.928792
10,Northgate Park,neighborhood,All Homes,125100,125500,125900,126200,126500,126700,126600,...,187500,189500,191500,194200,197000,198600,199900,201300,36.022560,-78.905942
11,Old Farm,neighborhood,All Homes,130200,130600,131200,131700,132000,132000,131700,...,164000,163400,163900,165500,167300,169700,173000,175900,36.069543,-78.904940
12,Old North Durham,neighborhood,All Homes,135400,136600,138000,139300,140600,141800,143000,...,285700,288600,289600,290300,290700,292200,297500,302900,36.004769,-78.896925
13,Omah Street,neighborhood,All Homes,102500,103500,104300,105100,106000,106900,107900,...,127400,127900,128200,129700,132000,134900,138600,142000,36.031035,-78.932065
14,Parkwood,neighborhood,All Homes,147100,147300,147400,147300,147300,147200,147000,...,204600,205800,206200,206600,207700,209100,211600,214400,35.892273,-78.927913
15,Penrith,neighborhood,All Homes,168700,168200,167700,167300,166900,166400,165500,...,222200,223700,224000,224400,225000,225800,227700,230300,35.921871,-78.900489
16,Scarsdale Village,neighborhood,All Homes,137500,137900,138200,138400,138600,139000,139300,...,178900,180400,181400,182400,183200,183900,185200,186700,36.047298,-78.925498
17,Stadium Heights,neighborhood,All Homes,119400,119800,120200,120500,120800,121000,121100,...,146500,150700,154300,156300,157100,158300,160500,163000,36.040479,-78.914006
18,Trinity Park,neighborhood,All Homes,252600,253500,254200,254800,255700,256400,256700,...,379600,382700,384100,384200,382300,383500,391400,400100,36.009143,-78.915844
19,Walltown,neighborhood,All Homes,107200,108600,109800,110800,111600,112400,113000,...,216400,222400,227700,232500,236400,239700,243600,247100,36.018533,-78.923891
20,Watts Hospital-Hillandale,neighborhood,All Homes,198200,199400,200500,201400,202200,202900,203400,...,302900,303300,303200,303500,304300,304600,304400,304700,36.022102,-78.939279
21,Woodcroft,neighborhood,All Homes,176800,177100,177600,178100,178500,178600,178700,...,208900,209700,209500,208800,208000,207400,208700,211600,35.923319,-78.947527
22,Woodlake,neighborhood,All Homes,196400,196100,195800,195500,195200,194600,194100,...,244400,245600,246200,246700,247500,248500,250300,252000,35.921035,-78.924289

In [10]:
house.drop([0], axis=0, inplace=True)

In [11]:
house

,Region Name,Region Type,Data Type,2008-10-15 00:00:00,2008-11-15 00:00:00,2008-12-15 00:00:00,2009-01-15 00:00:00,2009-02-15 00:00:00,2009-03-15 00:00:00,2009-04-15 00:00:00,...,2018-02-15 00:00:00,2018-03-15 00:00:00,2018-04-15 00:00:00,2018-05-15 00:00:00,2018-06-15 00:00:00,2018-07-15 00:00:00,2018-08-15 00:00:00,2018-09-15 00:00:00,Latitude,Longitude
1,American Village,neighborhood,All Homes,255700,255900,256000,256200,256200,256100,255900,...,310700,312000,313000,314900,317400,319500,321600,323500,36.017087,-78.969454
2,Colonial Village,neighborhood,All Homes,109100,110000,110900,111600,112300,112900,113800,...,152500,151100,151400,152800,153000,153300,155200,156800,35.189505,-80.869604
3,Duke Forest,neighborhood,All Homes,340200,341300,342400,343300,343900,344500,344900,...,453300,465500,476800,484100,487600,492100,498400,503800,35.585900,-79.018600
4,Duke Park,neighborhood,All Homes,154000,154300,154600,155000,155600,156100,156400,...,273800,275200,273700,271200,269500,269200,271800,275600,36.013667,-78.899723
5,Fairfield,neighborhood,All Homes,310600,309600,308600,307900,307400,306700,305700,...,368900,372000,373900,374700,375200,376500,378100,379400,36.047507,-78.906627
6,Forest Hills,neighborhood,All Homes,260000,261800,263600,265100,266500,267800,268700,...,403800,405100,404800,402300,402600,406400,412900,418600,35.980379,-78.924012
7,Grove Park,neighborhood,All Homes,179900,180000,180100,180200,180100,180200,180200,...,217600,220500,222200,223800,225500,227400,230100,232500,35.973712,-78.818301
8,Hope Valley,neighborhood,All Homes,217700,217500,217300,217000,216700,216200,215600,...,267700,268500,269800,271700,273300,275200,277600,279400,35.949787,-78.961095
9,Hope Valley Farms,neighborhood,All Homes,204300,204400,204500,204500,204500,204300,204000,...,249100,250100,250700,250700,250600,251300,253300,255200,35.946093,-78.928792
10,Northgate Park,neighborhood,All Homes,125100,125500,125900,126200,126500,126700,126600,...,187500,189500,191500,194200,197000,198600,199900,201300,36.022560,-78.905942
11,Old Farm,neighborhood,All Homes,130200,130600,131200,131700,132000,132000,131700,...,164000,163400,163900,165500,167300,169700,173000,175900,36.069543,-78.904940
12,Old North Durham,neighborhood,All Homes,135400,136600,138000,139300,140600,141800,143000,...,285700,288600,289600,290300,290700,292200,297500,302900,36.004769,-78.896925
13,Omah Street,neighborhood,All Homes,102500,103500,104300,105100,106000,106900,107900,...,127400,127900,128200,129700,132000,134900,138600,142000,36.031035,-78.932065
14,Parkwood,neighborhood,All Homes,147100,147300,147400,147300,147300,147200,147000,...,204600,205800,206200,206600,207700,209100,211600,214400,35.892273,-78.927913
15,Penrith,neighborhood,All Homes,168700,168200,167700,167300,166900,166400,165500,...,222200,223700,224000,224400,225000,225800,227700,230300,35.921871,-78.900489
16,Scarsdale Village,neighborhood,All Homes,137500,137900,138200,138400,138600,139000,139300,...,178900,180400,181400,182400,183200,183900,185200,186700,36.047298,-78.925498
17,Stadium Heights,neighborhood,All Homes,119400,119800,120200,120500,120800,121000,121100,...,146500,150700,154300,156300,157100,158300,160500,163000,36.040479,-78.914006
18,Trinity Park,neighborhood,All Homes,252600,253500,254200,254800,255700,256400,256700,...,379600,382700,384100,384200,382300,383500,391400,400100,36.009143,-78.915844
19,Walltown,neighborhood,All Homes,107200,108600,109800,110800,111600,112400,113000,...,216400,222400,227700,232500,236400,239700,243600,247100,36.018533,-78.923891
20,Watts Hospital-Hillandale,neighborhood,All Homes,198200,199400,200500,201400,202200,202900,203400,...,302900,303300,303200,303500,304300,304600,304400,304700,36.022102,-78.939279
21,Woodcroft,neighborhood,All Homes,176800,177100,177600,178100,178500,178600,178700,...,208900,209700,209500,208800,208000,207400,208700,211600,35.923319,-78.947527
22,Woodlake,neighborhood,All Homes,196400,196100,195800,195500,195200,194600,194100,...,244400,245600,246200,246700,247500,248500,250300,252000,35.921035,-78.924289

In [13]:
print(house.describe())

       2008-10-15 00:00:00  2008-11-15 00:00:00  2008-12-15 00:00:00  \
count            22.000000            22.000000            22.000000
mean         183118.181818        183586.363636        184036.363636
std           66801.337571         66704.974438         66611.585904
min          102500.000000        103500.000000        104300.000000
25%          131500.000000        132100.000000        132900.000000
50%          172750.000000        172650.000000        172650.000000
75%          214350.000000        214225.000000        214100.000000
max          340200.000000        341300.000000        342400.000000

       2009-01-15 00:00:00  2009-02-15 00:00:00  2009-03-15 00:00:00  \
count            22.000000            22.000000            22.000000
mean         184418.181818        184777.272727        185031.818182
std           66546.751460         66474.362633         66385.435769
min          105100.000000        106000.000000        106900.000000
25%          133375.000000        133650.000000        133750.000000
50%          172700.000000        172700.000000        172500.000000
75%          213875.000000        213650.000000        213225.000000
max          343300.000000        343900.000000        344500.000000

       2009-04-15 00:00:00  2009-05-15 00:00:00  2009-06-15 00:00:00  \
count            22.000000            22.000000            22.000000
mean         185145.454545        185190.909091        185140.909091
std           66231.230781         65903.124495         65438.896683
min          107900.000000        109000.000000        109800.000000
25%          133600.000000        133675.000000        133900.000000
50%          172100.000000        171700.000000        171500.000000
75%          212700.000000        212100.000000        211575.000000
max          344900.000000        344600.000000        344100.000000

       2009-07-15 00:00:00    ...      2018-02-15 00:00:00  \
count            22.000000    ...                22.000000
mean         185036.363636    ...            253018.181818
std           64929.460226    ...             88019.541317
min          110500.000000    ...            127400.000000
25%          134225.000000    ...            191775.000000
50%          171650.000000    ...            233300.000000
75%          211025.000000    ...            298600.000000
max          344100.000000    ...            453300.000000

       2018-03-15 00:00:00  2018-04-15 00:00:00  2018-05-15 00:00:00  \
count            22.000000            22.000000            22.000000
mean         255168.181818        256640.909091        257786.363636
std           89450.424612         90465.213831         90660.645610
min          127900.000000        128200.000000        129700.000000
25%          193575.000000        195175.000000        197300.000000
50%          234650.000000        236950.000000        239600.000000
75%          299625.000000        299800.000000        300200.000000
max          465500.000000        476800.000000        484100.000000

       2018-06-15 00:00:00  2018-07-15 00:00:00  2018-08-15 00:00:00  \
count            22.000000            22.000000            22.000000
mean         258781.818182        260322.727273        263245.454545
std           90589.900816         91107.095180         92203.908229
min          132000.000000        134900.000000        138600.000000
25%          199675.000000        200800.000000        202100.000000
50%          241950.000000        244100.000000        246950.000000
75%          300900.000000        301500.000000        302675.000000
max          487600.000000        492100.000000        498400.000000

       2018-09-15 00:00:00   Latitude  Longitude
count            22.000000  22.000000  22.000000
mean         266218.181818  35.937618 -79.011583
std           93172.889151   0.194319   0.416568
min          142000.000000  35.189505 -80.869604
25%          203875.000000  35.929012 -78.937475
50%          249550.000000  36.006956 -78.924150
75%          304250.000000  36.022445 -78.906113
max          503800.000000  36.069543 -78.818301

[8 rows x 122 columns]